import {Injectable} from '@angular/core';
import {Model} from "../interface/model.interface";
import {BehaviorSubject} from "rxjs";
import {BrandAndModel} from "../interface/brand-and-model.interface";

@Injectable({
  providedIn: 'root'
})
export class ModelService {

  selectedMarque!:any;
  selectedModels:any;

  //A rajouter dans bdd
  public brandAndModel: BehaviorSubject<BrandAndModel[]> = new BehaviorSubject([
    {brandId: 1, brand: "ALFA ROMEO", modelId: 1, model: "145"},
    {brandId: 1, brand: "ALFA ROMEO", modelId: 2, model: "146"},
    {brandId: 1, brand: "ALFA ROMEO", modelId: 3, model: "147"},
    {brandId: 1, brand: "ALFA ROMEO", modelId: 4, model: "155"},
    {brandId: 1, brand: "ALFA ROMEO", modelId: 5, model: "156"},
    {brandId: 1, brand: "ALFA ROMEO", modelId: 6, model: "159"},
    {brandId: 1, brand: "ALFA ROMEO", modelId: 7, model: "164"},
    {brandId: 1, brand: "ALFA ROMEO", modelId: 8, model: "166"},
    {brandId: 1, brand: "ALFA ROMEO", modelId: 9, model: "33"},
    {brandId: 1, brand: "ALFA ROMEO", modelId: 10, model: "4c"},
    {brandId: 1, brand: "ALFA ROMEO", modelId: 11, model: "6"},
    {brandId: 1, brand: "ALFA ROMEO", modelId: 12, model: "75"},
    {brandId: 1, brand: "ALFA ROMEO", modelId: 13, model: "8C"},
    {brandId: 1, brand: "ALFA ROMEO", modelId: 14, model: "8c Spider"},
    {brandId: 1, brand: "ALFA ROMEO", modelId: 15, model: "90"},
    {brandId: 1, brand: "ALFA ROMEO", modelId: 16, model: "Alfa"},
    {brandId: 1, brand: "ALFA ROMEO", modelId: 17, model: "Alfa-6"},
    {brandId: 1, brand: "ALFA ROMEO", modelId: 18, model: "Alfasud"},
    {brandId: 1, brand: "ALFA ROMEO", modelId: 19, model: "Alfetta"},
    {brandId: 1, brand: "ALFA ROMEO", modelId: 20, model: "Brera"},
    {brandId: 1, brand: "ALFA ROMEO", modelId: 21, model: "Coupe"},
    {brandId: 1, brand: "ALFA ROMEO", modelId: 22, model: "Crosswagon Q4"},
    {brandId: 1, brand: "ALFA ROMEO", modelId: 23, model: "GT"},
    {brandId: 1, brand: "ALFA ROMEO", modelId: 24, model: "Giulia"},
    {brandId: 1, brand: "ALFA ROMEO", modelId: 25, model: "Giulietta"},
    {brandId: 1, brand: "ALFA ROMEO", modelId: 26, model: "Gtv"},
    {brandId: 1, brand: "ALFA ROMEO", modelId: 27, model: "Mito"},
    {brandId: 1, brand: "ALFA ROMEO", modelId: 28, model: "Spider"},
    {brandId: 1, brand: "ALFA ROMEO", modelId: 29, model: "Sport-Wagon"},
    {brandId: 1, brand: "ALFA ROMEO", modelId: 30, model: "Sportwagon Q4"},
    {brandId: 1, brand: "ALFA ROMEO", modelId: 31, model: "Sprint"},
    {brandId: 1, brand: "ALFA ROMEO", modelId: 32, model: "Stelvio"},
    {brandId: 1, brand: "ALFA ROMEO", modelId: 33, model: "Sud"},
    {brandId: 1, brand: "ALFA ROMEO", modelId: 34, model: "Zagato"},
    {brandId: 2, brand: "ASTON MARTIN", modelId: 35, model: "Cygnet"},
    {brandId: 2, brand: "ASTON MARTIN", modelId: 36, model: "Db11"},
    {brandId: 2, brand: "ASTON MARTIN", modelId: 37, model: "Db7"},
    {brandId: 2, brand: "ASTON MARTIN", modelId: 38, model: "Db9"},
    {brandId: 2, brand: "ASTON MARTIN", modelId: 39, model: "Dbs"},
    {brandId: 2, brand: "ASTON MARTIN", modelId: 40, model: "Lagonda"},
    {brandId: 2, brand: "ASTON MARTIN", modelId: 41, model: "Rapide"},
    {brandId: 2, brand: "ASTON MARTIN", modelId: 42, model: "V8"},
    {brandId: 2, brand: "ASTON MARTIN", modelId: 43, model: "Vanquish"},
    {brandId: 2, brand: "ASTON MARTIN", modelId: 44, model: "Vantage"},
    {brandId: 2, brand: "ASTON MARTIN", modelId: 45, model: "Virage"},
    {brandId: 3, brand: "AUDI", modelId: 46, model: "100"},
    {brandId: 3, brand: "AUDI", modelId: 47, model: "200"},
    {brandId: 3, brand: "AUDI", modelId: 48, model: "80"},
    {brandId: 3, brand: "AUDI", modelId: 49, model: "90"},
    {brandId: 3, brand: "AUDI", modelId: 50, model: "A1"},
    {brandId: 3, brand: "AUDI", modelId: 51, model: "A2"},
    {brandId: 3, brand: "AUDI", modelId: 52, model: "A3"},
    {brandId: 3, brand: "AUDI", modelId: 53, model: "A4"},
    {brandId: 3, brand: "AUDI", modelId: 54, model: "A5"},
    {brandId: 3, brand: "AUDI", modelId: 55, model: "A6"},
    {brandId: 3, brand: "AUDI", modelId: 56, model: "A6/s6"},
    {brandId: 3, brand: "AUDI", modelId: 57, model: "A7"},
    {brandId: 3, brand: "AUDI", modelId: 58, model: "A8"},
    {brandId: 3, brand: "AUDI", modelId: 59, model: "Allroad"},
    {brandId: 3, brand: "AUDI", modelId: 60, model: "Cabriolet"},
    {brandId: 3, brand: "AUDI", modelId: 61, model: "Coupe"},
    {brandId: 3, brand: "AUDI", modelId: 62, model: "E-Tron"},
    {brandId: 3, brand: "AUDI", modelId: 63, model: "Q2"},
    {brandId: 3, brand: "AUDI", modelId: 64, model: "Q3"},
    {brandId: 3, brand: "AUDI", modelId: 65, model: "Q5"},
    {brandId: 3, brand: "AUDI", modelId: 66, model: "Q7"},
    {brandId: 3, brand: "AUDI", modelId: 67, model: "Q8"},
    {brandId: 3, brand: "AUDI", modelId: 68, model: "R8"},
    {brandId: 3, brand: "AUDI", modelId: 69, model: "Rs3"},
    {brandId: 3, brand: "AUDI", modelId: 70, model: "Rs4"},
    {brandId: 3, brand: "AUDI", modelId: 71, model: "Rs5"},
    {brandId: 3, brand: "AUDI", modelId: 72, model: "Rs7"},
    {brandId: 3, brand: "AUDI", modelId: 73, model: "S3"},
    {brandId: 3, brand: "AUDI", modelId: 74, model: "S4"},
    {brandId: 3, brand: "AUDI", modelId: 75, model: "S4 Avant"},
    {brandId: 3, brand: "AUDI", modelId: 76, model: "S4 Cabriolet"},
    {brandId: 3, brand: "AUDI", modelId: 77, model: "S5"},
    {brandId: 3, brand: "AUDI", modelId: 78, model: "S7"},
    {brandId: 3, brand: "AUDI", modelId: 79, model: "S8"},
    {brandId: 3, brand: "AUDI", modelId: 80, model: "SQ5"},
    {brandId: 3, brand: "AUDI", modelId: 81, model: "SQ7"},
    {brandId: 3, brand: "AUDI", modelId: 82, model: "Tt"},
    {brandId: 3, brand: "AUDI", modelId: 83, model: "Tts"},
    {brandId: 3, brand: "AUDI", modelId: 84, model: "V8"},
    {brandId: 4, brand: "BENTLEY", modelId: 85, model: "Arnage"},
    {brandId: 4, brand: "BENTLEY", modelId: 86, model: "Azure"},
    {brandId: 4, brand: "BENTLEY", modelId: 87, model: "Bentayga"},
    {brandId: 4, brand: "BENTLEY", modelId: 88, model: "Brooklands"},
    {brandId: 4, brand: "BENTLEY", modelId: 89, model: "Continental"},
    {brandId: 4, brand: "BENTLEY", modelId: 90, model: "Coupe"},
    {brandId: 4, brand: "BENTLEY", modelId: 91, model: "Eight"},
    {brandId: 4, brand: "BENTLEY", modelId: 92, model: "Flying Spur"},
    {brandId: 4, brand: "BENTLEY", modelId: 93, model: "Mulsanne"},
    {brandId: 4, brand: "BENTLEY", modelId: 94, model: "Turbo"},
    {brandId: 5, brand: "BMW", modelId: 95, model: "316"},
    {brandId: 5, brand: "BMW", modelId: 96, model: "318"},
    {brandId: 5, brand: "BMW", modelId: 97, model: "320"},
    {brandId: 5, brand: "BMW", modelId: 98, model: "323"},
    {brandId: 5, brand: "BMW", modelId: 99, model: "324"},
    {brandId: 5, brand: "BMW", modelId: 100, model: "325"},
    {brandId: 5, brand: "BMW", modelId: 101, model: "518"},
    {brandId: 5, brand: "BMW", modelId: 102, model: "520"},
    {brandId: 5, brand: "BMW", modelId: 103, model: "524"},
    {brandId: 5, brand: "BMW", modelId: 104, model: "525"},
    {brandId: 5, brand: "BMW", modelId: 105, model: "528"},
    {brandId: 5, brand: "BMW", modelId: 106, model: "530"},
    {brandId: 5, brand: "BMW", modelId: 107, model: "535"},
    {brandId: 5, brand: "BMW", modelId: 108, model: "540"},
    {brandId: 5, brand: "BMW", modelId: 109, model: "628"},
    {brandId: 5, brand: "BMW", modelId: 110, model: "635"},
    {brandId: 5, brand: "BMW", modelId: 111, model: "728"},
    {brandId: 5, brand: "BMW", modelId: 112, model: "730"},
    {brandId: 5, brand: "BMW", modelId: 113, model: "732"},
    {brandId: 5, brand: "BMW", modelId: 114, model: "735"},
    {brandId: 5, brand: "BMW", modelId: 115, model: "740"},
    {brandId: 5, brand: "BMW", modelId: 116, model: "745"},
    {brandId: 5, brand: "BMW", modelId: 117, model: "750"},
    {brandId: 5, brand: "BMW", modelId: 118, model: "840"},
    {brandId: 5, brand: "BMW", modelId: 119, model: "850"},
    {brandId: 5, brand: "BMW", modelId: 120, model: "I3"},
    {brandId: 5, brand: "BMW", modelId: 121, model: "I8"},
    {brandId: 5, brand: "BMW", modelId: 122, model: "M3"},
    {brandId: 5, brand: "BMW", modelId: 123, model: "M4"},
    {brandId: 5, brand: "BMW", modelId: 124, model: "M5"},
    {brandId: 5, brand: "BMW", modelId: 125, model: "M535"},
    {brandId: 5, brand: "BMW", modelId: 126, model: "M6"},
    {brandId: 5, brand: "BMW", modelId: 127, model: "M635"},
    {brandId: 5, brand: "BMW", modelId: 128, model: "Serie 1"},
    {brandId: 5, brand: "BMW", modelId: 129, model: "Serie 2"},
    {brandId: 5, brand: "BMW", modelId: 130, model: "Serie 3"},
    {brandId: 5, brand: "BMW", modelId: 131, model: "Serie 4"},
    {brandId: 5, brand: "BMW", modelId: 132, model: "Serie 5"},
    {brandId: 5, brand: "BMW", modelId: 133, model: "Serie 6"},
    {brandId: 5, brand: "BMW", modelId: 134, model: "Serie 7"},
    {brandId: 5, brand: "BMW", modelId: 135, model: "Serie 8"},
    {brandId: 5, brand: "BMW", modelId: 136, model: "X1"},
    {brandId: 5, brand: "BMW", modelId: 137, model: "X2"},
    {brandId: 5, brand: "BMW", modelId: 138, model: "X3"},
    {brandId: 5, brand: "BMW", modelId: 139, model: "X4"},
    {brandId: 5, brand: "BMW", modelId: 140, model: "X5"},
    {brandId: 5, brand: "BMW", modelId: 141, model: "X6"},
    {brandId: 5, brand: "BMW", modelId: 142, model: "X7"},
    {brandId: 5, brand: "BMW", modelId: 143, model: "Z-series"},
    {brandId: 5, brand: "BMW", modelId: 144, model: "Z1"},
    {brandId: 5, brand: "BMW", modelId: 145, model: "Z3"},
    {brandId: 5, brand: "BMW", modelId: 146, model: "Z4"},
    {brandId: 5, brand: "BMW", modelId: 147, model: "Z8"},
    {brandId: 5, brand: "BMW", modelId: 148, model: "ZI Cabriolet"},
    {brandId: 6, brand: "CHEVROLET", modelId: 149, model: "Alero"},
    {brandId: 6, brand: "CHEVROLET", modelId: 150, model: "Aveo"},
    {brandId: 6, brand: "CHEVROLET", modelId: 151, model: "Blazer"},
    {brandId: 6, brand: "CHEVROLET", modelId: 152, model: "Camaro"},
    {brandId: 6, brand: "CHEVROLET", modelId: 153, model: "Captiva"},
    {brandId: 6, brand: "CHEVROLET", modelId: 154, model: "Corsica"},
    {brandId: 6, brand: "CHEVROLET", modelId: 155, model: "Corvette"},
    {brandId: 6, brand: "CHEVROLET", modelId: 156, model: "Cruze"},
    {brandId: 6, brand: "CHEVROLET", modelId: 157, model: "Epica"},
    {brandId: 6, brand: "CHEVROLET", modelId: 158, model: "Evanda"},
    {brandId: 6, brand: "CHEVROLET", modelId: 159, model: "Kalos"},
    {brandId: 6, brand: "CHEVROLET", modelId: 160, model: "Lacetti"},
    {brandId: 6, brand: "CHEVROLET", modelId: 161, model: "Malibu"},
    {brandId: 6, brand: "CHEVROLET", modelId: 162, model: "Matiz"},
    {brandId: 6, brand: "CHEVROLET", modelId: 163, model: "Nubira"},
    {brandId: 6, brand: "CHEVROLET", modelId: 164, model: "Orlando"},
    {brandId: 6, brand: "CHEVROLET", modelId: 165, model: "Rezzo"},
    {brandId: 6, brand: "CHEVROLET", modelId: 166, model: "Spark"},
    {brandId: 6, brand: "CHEVROLET", modelId: 167, model: "Tahoe"},
    {brandId: 6, brand: "CHEVROLET", modelId: 168, model: "Transsport"},
    {brandId: 6, brand: "CHEVROLET", modelId: 169, model: "Trax"},
    {brandId: 6, brand: "CHEVROLET", modelId: 170, model: "Volt"},
    {brandId: 7, brand: "CHRYSLER", modelId: 171, model: "300c"},
    {brandId: 7, brand: "CHRYSLER", modelId: 172, model: "300m"},
    {brandId: 7, brand: "CHRYSLER", modelId: 173, model: "Crossfire"},
    {brandId: 7, brand: "CHRYSLER", modelId: 174, model: "Es"},
    {brandId: 7, brand: "CHRYSLER", modelId: 175, model: "Grand Voyager"},
    {brandId: 7, brand: "CHRYSLER", modelId: 176, model: "Le Baron"},
    {brandId: 7, brand: "CHRYSLER", modelId: 177, model: "Neon"},
    {brandId: 7, brand: "CHRYSLER", modelId: 178, model: "New Yorker"},
    {brandId: 7, brand: "CHRYSLER", modelId: 179, model: "Pt Cruiser"},
    {brandId: 7, brand: "CHRYSLER", modelId: 180, model: "Saratoga"},
    {brandId: 7, brand: "CHRYSLER", modelId: 181, model: "Sebring"},
    {brandId: 7, brand: "CHRYSLER", modelId: 182, model: "Stratus"},
    {brandId: 7, brand: "CHRYSLER", modelId: 183, model: "Viper"},
    {brandId: 7, brand: "CHRYSLER", modelId: 184, model: "Vision"},
    {brandId: 7, brand: "CHRYSLER", modelId: 185, model: "Voyager"},
    {brandId: 8, brand: "CITROËN", modelId: 186, model: "2cv"},
    {brandId: 8, brand: "CITROËN", modelId: 187, model: "Ax"},
    {brandId: 8, brand: "CITROËN", modelId: 188, model: "Axel"},
    {brandId: 8, brand: "CITROËN", modelId: 189, model: "Berlingo"},
    {brandId: 8, brand: "CITROËN", modelId: 190, model: "Bx"},
    {brandId: 8, brand: "CITROËN", modelId: 191, model: "C-crosser"},
    {brandId: 8, brand: "CITROËN", modelId: 192, model: "C-elysee"},
    {brandId: 8, brand: "CITROËN", modelId: 193, model: "C-zero"},
    {brandId: 8, brand: "CITROËN", modelId: 194, model: "C1"},
    {brandId: 8, brand: "CITROËN", modelId: 195, model: "C15"},
    {brandId: 8, brand: "CITROËN", modelId: 196, model: "C2"},
    {brandId: 8, brand: "CITROËN", modelId: 197, model: "C25"},
    {brandId: 8, brand: "CITROËN", modelId: 198, model: "C25D"},
    {brandId: 8, brand: "CITROËN", modelId: 199, model: "C25E"},
    {brandId: 8, brand: "CITROËN", modelId: 200, model: "C25TD"},
    {brandId: 8, brand: "CITROËN", modelId: 201, model: "C3"},
    {brandId: 8, brand: "CITROËN", modelId: 202, model: "C3 Aircross"},
    {brandId: 8, brand: "CITROËN", modelId: 203, model: "C3 Picasso"},
    {brandId: 8, brand: "CITROËN", modelId: 204, model: "C4"},
    {brandId: 8, brand: "CITROËN", modelId: 205, model: "C4 Picasso"},
    {brandId: 8, brand: "CITROËN", modelId: 206, model: "C5"},
    {brandId: 8, brand: "CITROËN", modelId: 207, model: "C6"},
    {brandId: 8, brand: "CITROËN", modelId: 208, model: "C8"},
    {brandId: 8, brand: "CITROËN", modelId: 209, model: "Combi"},
    {brandId: 8, brand: "CITROËN", modelId: 210, model: "Cx"},
    {brandId: 8, brand: "CITROËN", modelId: 211, model: "Ds3"},
    {brandId: 8, brand: "CITROËN", modelId: 212, model: "Ds4"},
    {brandId: 8, brand: "CITROËN", modelId: 213, model: "Ds5"},
    {brandId: 8, brand: "CITROËN", modelId: 214, model: "Dyane"},
    {brandId: 8, brand: "CITROËN", modelId: 215, model: "Evasion"},
    {brandId: 8, brand: "CITROËN", modelId: 216, model: "Gsa"},
    {brandId: 8, brand: "CITROËN", modelId: 217, model: "Jumper"},
    {brandId: 8, brand: "CITROËN", modelId: 218, model: "Jumpy"},
    {brandId: 8, brand: "CITROËN", modelId: 219, model: "Lna"},
    {brandId: 8, brand: "CITROËN", modelId: 220, model: "Mehari"},
    {brandId: 8, brand: "CITROËN", modelId: 221, model: "E-mehari"},
    {brandId: 8, brand: "CITROËN", modelId: 222, model: "Nemo Combi"},
    {brandId: 8, brand: "CITROËN", modelId: 223, model: "Picasso"},
    {brandId: 8, brand: "CITROËN", modelId: 224, model: "Saxo"},
    {brandId: 8, brand: "CITROËN", modelId: 225, model: "Spacetourer"},
    {brandId: 8, brand: "CITROËN", modelId: 226, model: "Visa"},
    {brandId: 8, brand: "CITROËN", modelId: 227, model: "Xantia"},
    {brandId: 8, brand: "CITROËN", modelId: 228, model: "Xm"},
    {brandId: 8, brand: "CITROËN", modelId: 229, model: "Xsara"},
    {brandId: 8, brand: "CITROËN", modelId: 230, model: "Zx"},
    {brandId: 9, brand: "DACIA", modelId: 231, model: "Dokker"},
    {brandId: 9, brand: "DACIA", modelId: 232, model: "Duster"},
    {brandId: 9, brand: "DACIA", modelId: 233, model: "Lodgy"},
    {brandId: 9, brand: "DACIA", modelId: 234, model: "Logan"},
    {brandId: 9, brand: "DACIA", modelId: 235, model: "Sandero"},
    {brandId: 10, brand: "DAEWOO", modelId: 236, model: "Espero"},
    {brandId: 10, brand: "DAEWOO", modelId: 237, model: "Evanda"},
    {brandId: 10, brand: "DAEWOO", modelId: 238, model: "Kalos"},
    {brandId: 10, brand: "DAEWOO", modelId: 239, model: "Korando"},
    {brandId: 10, brand: "DAEWOO", modelId: 240, model: "Lacetti"},
    {brandId: 10, brand: "DAEWOO", modelId: 241, model: "Lanos"},
    {brandId: 10, brand: "DAEWOO", modelId: 242, model: "Leganza"},
    {brandId: 10, brand: "DAEWOO", modelId: 243, model: "Matiz"},
    {brandId: 10, brand: "DAEWOO", modelId: 244, model: "Musso"},
    {brandId: 10, brand: "DAEWOO", modelId: 245, model: "Nexia"},
    {brandId: 10, brand: "DAEWOO", modelId: 246, model: "Nubira"},
    {brandId: 10, brand: "DAEWOO", modelId: 247, model: "Rexton"},
    {brandId: 10, brand: "DAEWOO", modelId: 248, model: "Rezzo"},
    {brandId: 10, brand: "DAEWOO", modelId: 249, model: "Tacuma"},
    {brandId: 11, brand: "DS AUTO", modelId: 250, model: "Ds3"},
    {brandId: 11, brand: "DS AUTO", modelId: 251, model: "Ds4"},
    {brandId: 11, brand: "DS AUTO", modelId: 252, model: "Ds5"},
    {brandId: 11, brand: "DS AUTO", modelId: 253, model: "Ds7"},
    {brandId: 12, brand: "FERRARI", modelId: 254, model: "308"},
    {brandId: 12, brand: "FERRARI", modelId: 255, model: "328"},
    {brandId: 12, brand: "FERRARI", modelId: 256, model: "348"},
    {brandId: 12, brand: "FERRARI", modelId: 257, model: "400"},
    {brandId: 12, brand: "FERRARI", modelId: 258, model: "412"},
    {brandId: 12, brand: "FERRARI", modelId: 259, model: "456"},
    {brandId: 12, brand: "FERRARI", modelId: 260, model: "458"},
    {brandId: 12, brand: "FERRARI", modelId: 261, model: "458 Italia"},
    {brandId: 12, brand: "FERRARI", modelId: 262, model: "458 Speciale"},
    {brandId: 12, brand: "FERRARI", modelId: 263, model: "458 Spider"},
    {brandId: 12, brand: "FERRARI", modelId: 264, model: "488"},
    {brandId: 12, brand: "FERRARI", modelId: 265, model: "575"},
    {brandId: 12, brand: "FERRARI", modelId: 266, model: "599"},
    {brandId: 12, brand: "FERRARI", modelId: 267, model: "612"},
    {brandId: 12, brand: "FERRARI", modelId: 268, model: "812 Superfast"},
    {brandId: 12, brand: "FERRARI", modelId: 269, model: "Bb 512"},
    {brandId: 12, brand: "FERRARI", modelId: 270, model: "California"},
    {brandId: 12, brand: "FERRARI", modelId: 271, model: "Enzo"},
    {brandId: 12, brand: "FERRARI", modelId: 272, model: "F12"},
    {brandId: 12, brand: "FERRARI", modelId: 273, model: "F355"},
    {brandId: 12, brand: "FERRARI", modelId: 274, model: "F360"},
    {brandId: 12, brand: "FERRARI", modelId: 275, model: "F430"},
    {brandId: 12, brand: "FERRARI", modelId: 276, model: "F550"},
    {brandId: 12, brand: "FERRARI", modelId: 277, model: "Ff"},
    {brandId: 12, brand: "FERRARI", modelId: 278, model: "GTC4Lusso"},
    {brandId: 12, brand: "FERRARI", modelId: 279, model: "Mondial"},
    {brandId: 12, brand: "FERRARI", modelId: 280, model: "Portofino"},
    {brandId: 12, brand: "FERRARI", modelId: 281, model: "Testarossa"},
    {brandId: 13, brand: "FIAT", modelId: 282, model: "124"},
    {brandId: 13, brand: "FIAT", modelId: 283, model: "124 Spider"},
    {brandId: 13, brand: "FIAT", modelId: 284, model: "126"},
    {brandId: 13, brand: "FIAT", modelId: 285, model: "127"},
    {brandId: 13, brand: "FIAT", modelId: 286, model: "131"},
    {brandId: 13, brand: "FIAT", modelId: 287, model: "132"},
    {brandId: 13, brand: "FIAT", modelId: 288, model: "238"},
    {brandId: 13, brand: "FIAT", modelId: 289, model: "500"},
    {brandId: 13, brand: "FIAT", modelId: 290, model: "600"},
    {brandId: 13, brand: "FIAT", modelId: 291, model: "900"},
    {brandId: 13, brand: "FIAT", modelId: 292, model: "900.E"},
    {brandId: 13, brand: "FIAT", modelId: 293, model: "Argenta"},
    {brandId: 13, brand: "FIAT", modelId: 294, model: "Barchetta"},
    {brandId: 13, brand: "FIAT", modelId: 295, model: "Bertone"},
    {brandId: 13, brand: "FIAT", modelId: 296, model: "Brava"},
    {brandId: 13, brand: "FIAT", modelId: 297, model: "Bravo"},
    {brandId: 13, brand: "FIAT", modelId: 298, model: "Cinquecento"},
    {brandId: 13, brand: "FIAT", modelId: 299, model: "Coupe"},
    {brandId: 13, brand: "FIAT", modelId: 300, model: "Croma"},
    {brandId: 13, brand: "FIAT", modelId: 301, model: "Doblo"},
    {brandId: 13, brand: "FIAT", modelId: 302, model: "Ducato"},
    {brandId: 13, brand: "FIAT", modelId: 303, model: "Fiorino"},
    {brandId: 13, brand: "FIAT", modelId: 304, model: "Freemont"},
    {brandId: 13, brand: "FIAT", modelId: 305, model: "Fullback Vp"},
    {brandId: 13, brand: "FIAT", modelId: 306, model: "Grande Punto"},
    {brandId: 13, brand: "FIAT", modelId: 307, model: "Idea"},
    {brandId: 13, brand: "FIAT", modelId: 308, model: "Marea"},
    {brandId: 13, brand: "FIAT", modelId: 309, model: "Multipla"},
    {brandId: 13, brand: "FIAT", modelId: 310, model: "Palio"},
    {brandId: 13, brand: "FIAT", modelId: 311, model: "Panda"},
    {brandId: 13, brand: "FIAT", modelId: 312, model: "Punto"},
    {brandId: 13, brand: "FIAT", modelId: 313, model: "Punto Evo"},
    {brandId: 13, brand: "FIAT", modelId: 314, model: "Regata"},
    {brandId: 13, brand: "FIAT", modelId: 315, model: "Ritmo"},
    {brandId: 13, brand: "FIAT", modelId: 316, model: "Ritmo 2"},
    {brandId: 13, brand: "FIAT", modelId: 317, model: "Ritmo 3"},
    {brandId: 13, brand: "FIAT", modelId: 318, model: "Scudo"},
    {brandId: 13, brand: "FIAT", modelId: 319, model: "Sedici"},
    {brandId: 13, brand: "FIAT", modelId: 320, model: "Seicento"},
    {brandId: 13, brand: "FIAT", modelId: 321, model: "Spider"},
    {brandId: 13, brand: "FIAT", modelId: 322, model: "Stilo"},
    {brandId: 13, brand: "FIAT", modelId: 323, model: "Talento"},
    {brandId: 13, brand: "FIAT", modelId: 324, model: "Talento Vp"},
    {brandId: 13, brand: "FIAT", modelId: 325, model: "Tempra"},
    {brandId: 13, brand: "FIAT", modelId: 326, model: "Tipo"},
    {brandId: 13, brand: "FIAT", modelId: 327, model: "Ulysse"},
    {brandId: 13, brand: "FIAT", modelId: 328, model: "Uno"},
    {brandId: 13, brand: "FIAT", modelId: 329, model: "X1-9"},
    {brandId: 14, brand: "FORD", modelId: 330, model: "Aerostar"},
    {brandId: 14, brand: "FORD", modelId: 331, model: "B-max"},
    {brandId: 14, brand: "FORD", modelId: 332, model: "C-max"},
    {brandId: 14, brand: "FORD", modelId: 333, model: "Capri"},
    {brandId: 14, brand: "FORD", modelId: 334, model: "Cougar"},
    {brandId: 14, brand: "FORD", modelId: 335, model: "Courrier"},
    {brandId: 14, brand: "FORD", modelId: 336, model: "Custom"},
    {brandId: 14, brand: "FORD", modelId: 337, model: "Ecosport"},
    {brandId: 14, brand: "FORD", modelId: 338, model: "Edge"},
    {brandId: 14, brand: "FORD", modelId: 339, model: "Escort"},
    {brandId: 14, brand: "FORD", modelId: 340, model: "Explorer"},
    {brandId: 14, brand: "FORD", modelId: 341, model: "Fiesta"},
    {brandId: 14, brand: "FORD", modelId: 342, model: "Focus"},
    {brandId: 14, brand: "FORD", modelId: 343, model: "Fusion"},
    {brandId: 14, brand: "FORD", modelId: 344, model: "Galaxy"},
    {brandId: 14, brand: "FORD", modelId: 345, model: "Granada"},
    {brandId: 14, brand: "FORD", modelId: 346, model: "Grand C-max"},
    {brandId: 14, brand: "FORD", modelId: 347, model: "Gt"},
    {brandId: 14, brand: "FORD", modelId: 348, model: "Ka"},
    {brandId: 14, brand: "FORD", modelId: 349, model: "Ka+"},
    {brandId: 14, brand: "FORD", modelId: 350, model: "Kombi"},
    {brandId: 14, brand: "FORD", modelId: 351, model: "Kuga"},
    {brandId: 14, brand: "FORD", modelId: 352, model: "Maverick"},
    {brandId: 14, brand: "FORD", modelId: 353, model: "Minibus"},
    {brandId: 14, brand: "FORD", modelId: 354, model: "Mondeo"},
    {brandId: 14, brand: "FORD", modelId: 355, model: "Mustang"},
    {brandId: 14, brand: "FORD", modelId: 356, model: "Orion"},
    {brandId: 14, brand: "FORD", modelId: 357, model: "Probe"},
    {brandId: 14, brand: "FORD", modelId: 358, model: "Puma"},
    {brandId: 14, brand: "FORD", modelId: 359, model: "S-max"},
    {brandId: 14, brand: "FORD", modelId: 360, model: "Scorpio"},
    {brandId: 14, brand: "FORD", modelId: 361, model: "Sierra"},
    {brandId: 14, brand: "FORD", modelId: 362, model: "Streetka"},
    {brandId: 14, brand: "FORD", modelId: 363, model: "Taunus"},
    {brandId: 14, brand: "FORD", modelId: 364, model: "Tourneo"},
    {brandId: 14, brand: "FORD", modelId: 365, model: "Transit"},
    {brandId: 15, brand: "HONDA", modelId: 366, model: "Accord"},
    {brandId: 15, brand: "HONDA", modelId: 367, model: "Aerodeck"},
    {brandId: 15, brand: "HONDA", modelId: 368, model: "CRX"},
    {brandId: 15, brand: "HONDA", modelId: 369, model: "Civic"},
    {brandId: 15, brand: "HONDA", modelId: 370, model: "Concerto"},
    {brandId: 15, brand: "HONDA", modelId: 371, model: "Cr-v"},
    {brandId: 15, brand: "HONDA", modelId: 372, model: "Cr-z"},
    {brandId: 15, brand: "HONDA", modelId: 373, model: "Fr-v"},
    {brandId: 15, brand: "HONDA", modelId: 374, model: "Honda e"},
    {brandId: 15, brand: "HONDA", modelId: 375, model: "Hr-v"},
    {brandId: 15, brand: "HONDA", modelId: 376, model: "Insight"},
    {brandId: 15, brand: "HONDA", modelId: 377, model: "Integra"},
    {brandId: 15, brand: "HONDA", modelId: 378, model: "Jazz"},
    {brandId: 15, brand: "HONDA", modelId: 379, model: "Legend"},
    {brandId: 15, brand: "HONDA", modelId: 380, model: "Logo"},
    {brandId: 15, brand: "HONDA", modelId: 381, model: "Nsx"},
    {brandId: 15, brand: "HONDA", modelId: 382, model: "Prelude"},
    {brandId: 15, brand: "HONDA", modelId: 383, model: "Quintet"},
    {brandId: 15, brand: "HONDA", modelId: 384, model: "S2000"},
    {brandId: 15, brand: "HONDA", modelId: 385, model: "Shuttle"},
    {brandId: 15, brand: "HONDA", modelId: 386, model: "Stream"},
    {brandId: 16, brand: "HYUNDAI", modelId: 387, model: "Accent"},
    {brandId: 16, brand: "HYUNDAI", modelId: 388, model: "Atos"},
    {brandId: 16, brand: "HYUNDAI", modelId: 389, model: "Azera"},
    {brandId: 16, brand: "HYUNDAI", modelId: 390, model: "Coupe"},
    {brandId: 16, brand: "HYUNDAI", modelId: 391, model: "Elantra"},
    {brandId: 16, brand: "HYUNDAI", modelId: 392, model: "Galloper"},
    {brandId: 16, brand: "HYUNDAI", modelId: 393, model: "Genesis"},
    {brandId: 16, brand: "HYUNDAI", modelId: 394, model: "Getz"},
    {brandId: 16, brand: "HYUNDAI", modelId: 395, model: "Grandeur"},
    {brandId: 16, brand: "HYUNDAI", modelId: 396, model: "I10"},
    {brandId: 16, brand: "HYUNDAI", modelId: 397, model: "I20"},
    {brandId: 16, brand: "HYUNDAI", modelId: 398, model: "I30"},
    {brandId: 16, brand: "HYUNDAI", modelId: 399, model: "I40"},
    {brandId: 16, brand: "HYUNDAI", modelId: 400, model: "Ioniq"},
    {brandId: 16, brand: "HYUNDAI", modelId: 401, model: "Ix20"},
    {brandId: 16, brand: "HYUNDAI", modelId: 402, model: "Ix35"},
    {brandId: 16, brand: "HYUNDAI", modelId: 403, model: "Ix55"},
    {brandId: 16, brand: "HYUNDAI", modelId: 404, model: "Kona"},
    {brandId: 16, brand: "HYUNDAI", modelId: 405, model: "Lantra"},
    {brandId: 16, brand: "HYUNDAI", modelId: 406, model: "Matrix"},
    {brandId: 16, brand: "HYUNDAI", modelId: 407, model: "Nexo"},
    {brandId: 16, brand: "HYUNDAI", modelId: 408, model: "Pony"},
    {brandId: 16, brand: "HYUNDAI", modelId: 409, model: "Santa Fe"},
    {brandId: 16, brand: "HYUNDAI", modelId: 410, model: "Satellite"},
    {brandId: 16, brand: "HYUNDAI", modelId: 411, model: "Scoupe"},
    {brandId: 16, brand: "HYUNDAI", modelId: 412, model: "Sonata"},
    {brandId: 16, brand: "HYUNDAI", modelId: 413, model: "Terracan"},
    {brandId: 16, brand: "HYUNDAI", modelId: 414, model: "Trajet"},
    {brandId: 16, brand: "HYUNDAI", modelId: 415, model: "Tucson"},
    {brandId: 16, brand: "HYUNDAI", modelId: 416, model: "Veloster"},
    {brandId: 16, brand: "HYUNDAI", modelId: 417, model: "Xg"},
    {brandId: 17, brand: "JAGUAR", modelId: 418, model: "Daimler"},
    {brandId: 17, brand: "JAGUAR", modelId: 419, model: "E-pace"},
    {brandId: 17, brand: "JAGUAR", modelId: 420, model: "F-pace"},
    {brandId: 17, brand: "JAGUAR", modelId: 421, model: "F-type"},
    {brandId: 17, brand: "JAGUAR", modelId: 422, model: "I-Pace"},
    {brandId: 17, brand: "JAGUAR", modelId: 423, model: "S-type"},
    {brandId: 17, brand: "JAGUAR", modelId: 424, model: "Sovereign"},
    {brandId: 17, brand: "JAGUAR", modelId: 425, model: "V12"},
    {brandId: 17, brand: "JAGUAR", modelId: 426, model: "X-type"},
    {brandId: 17, brand: "JAGUAR", modelId: 427, model: "X308"},
    {brandId: 17, brand: "JAGUAR", modelId: 428, model: "XJRS"},
    {brandId: 17, brand: "JAGUAR", modelId: 429, model: "XJSC"},
    {brandId: 17, brand: "JAGUAR", modelId: 430, model: "Xe"},
    {brandId: 17, brand: "JAGUAR", modelId: 431, model: "Xf"},
    {brandId: 17, brand: "JAGUAR", modelId: 432, model: "Xj"},
    {brandId: 17, brand: "JAGUAR", modelId: 433, model: "Xj-s"},
    {brandId: 17, brand: "JAGUAR", modelId: 434, model: "Xj12"},
    {brandId: 17, brand: "JAGUAR", modelId: 435, model: "Xj40"},
    {brandId: 17, brand: "JAGUAR", modelId: 436, model: "Xjr"},
    {brandId: 17, brand: "JAGUAR", modelId: 437, model: "Xk8"},
    {brandId: 17, brand: "JAGUAR", modelId: 438, model: "Xkr"},
    {brandId: 18, brand: "JEEP", modelId: 439, model: "Cherokee"},
    {brandId: 18, brand: "JEEP", modelId: 440, model: "Commander"},
    {brandId: 18, brand: "JEEP", modelId: 441, model: "Compass"},
    {brandId: 18, brand: "JEEP", modelId: 442, model: "Compass Ii"},
    {brandId: 18, brand: "JEEP", modelId: 443, model: "Grand Cherokee"},
    {brandId: 18, brand: "JEEP", modelId: 444, model: "Patriot"},
    {brandId: 18, brand: "JEEP", modelId: 445, model: "Renegade"},
    {brandId: 18, brand: "JEEP", modelId: 446, model: "Wrangler"},
    {brandId: 19, brand: "KIA", modelId: 447, model: "Carens"},
    {brandId: 19, brand: "KIA", modelId: 448, model: "Carnival"},
    {brandId: 19, brand: "KIA", modelId: 449, model: "Cee D"},
    {brandId: 19, brand: "KIA", modelId: 450, model: "Cerato"},
    {brandId: 19, brand: "KIA", modelId: 451, model: "Clarus"},
    {brandId: 19, brand: "KIA", modelId: 452, model: "Leo"},
    {brandId: 19, brand: "KIA", modelId: 453, model: "Magentis"},
    {brandId: 19, brand: "KIA", modelId: 454, model: "Niro"},
    {brandId: 19, brand: "KIA", modelId: 455, model: "Opirus"},
    {brandId: 19, brand: "KIA", modelId: 456, model: "Optima"},
    {brandId: 19, brand: "KIA", modelId: 457, model: "Picanto"},
    {brandId: 19, brand: "KIA", modelId: 458, model: "Pride"},
    {brandId: 19, brand: "KIA", modelId: 459, model: "Pride Break"},
    {brandId: 19, brand: "KIA", modelId: 460, model: "Pro Cee D"},
    {brandId: 19, brand: "KIA", modelId: 461, model: "Rio"},
    {brandId: 19, brand: "KIA", modelId: 462, model: "Sephia"},
    {brandId: 19, brand: "KIA", modelId: 463, model: "Shuma"},
    {brandId: 19, brand: "KIA", modelId: 464, model: "Sorento"},
    {brandId: 19, brand: "KIA", modelId: 465, model: "Soul"},
    {brandId: 19, brand: "KIA", modelId: 466, model: "Sportage"},
    {brandId: 19, brand: "KIA", modelId: 467, model: "Stinger"},
    {brandId: 19, brand: "KIA", modelId: 468, model: "Stonic"},
    {brandId: 19, brand: "KIA", modelId: 469, model: "Venga"},
    {brandId: 19, brand: "KIA", modelId: 470, model: "XCeed"},
    {brandId: 20, brand: "MASERATI", modelId: 471, model: "222"},
    {brandId: 20, brand: "MASERATI", modelId: 472, model: "222 Coupe"},
    {brandId: 20, brand: "MASERATI", modelId: 473, model: "228"},
    {brandId: 20, brand: "MASERATI", modelId: 474, model: "3200 Gt"},
    {brandId: 20, brand: "MASERATI", modelId: 475, model: "422"},
    {brandId: 20, brand: "MASERATI", modelId: 476, model: "430"},
    {brandId: 20, brand: "MASERATI", modelId: 477, model: "Biturbo"},
    {brandId: 20, brand: "MASERATI", modelId: 478, model: "Coupe"},
    {brandId: 20, brand: "MASERATI", modelId: 479, model: "Ghibli"},
    {brandId: 20, brand: "MASERATI", modelId: 480, model: "Grancabrio"},
    {brandId: 20, brand: "MASERATI", modelId: 481, model: "Granturismo"},
    {brandId: 20, brand: "MASERATI", modelId: 482, model: "Levante"},
    {brandId: 20, brand: "MASERATI", modelId: 483, model: "Merak"},
    {brandId: 20, brand: "MASERATI", modelId: 484, model: "Quattroporte"},
    {brandId: 20, brand: "MASERATI", modelId: 485, model: "Shamal"},
    {brandId: 20, brand: "MASERATI", modelId: 486, model: "Spider Cabriolet"},
    {brandId: 20, brand: "MASERATI", modelId: 487, model: "Spyder"},
    {brandId: 21, brand: "MAZDA", modelId: 488, model: "121"},
    {brandId: 21, brand: "MAZDA", modelId: 489, model: "2"},
    {brandId: 21, brand: "MAZDA", modelId: 490, model: "3"},
    {brandId: 21, brand: "MAZDA", modelId: 491, model: "323"},
    {brandId: 21, brand: "MAZDA", modelId: 492, model: "5"},
    {brandId: 21, brand: "MAZDA", modelId: 493, model: "6"},
    {brandId: 21, brand: "MAZDA", modelId: 494, model: "626"},
    {brandId: 21, brand: "MAZDA", modelId: 495, model: "929"},
    {brandId: 21, brand: "MAZDA", modelId: 496, model: "CX-3"},
    {brandId: 21, brand: "MAZDA", modelId: 497, model: "CX-30"},
    {brandId: 21, brand: "MAZDA", modelId: 498, model: "Cx-5"},
    {brandId: 21, brand: "MAZDA", modelId: 499, model: "Cx-7"},
    {brandId: 21, brand: "MAZDA", modelId: 500, model: "Demio"},
    {brandId: 21, brand: "MAZDA", modelId: 501, model: "Mpv"},
    {brandId: 21, brand: "MAZDA", modelId: 502, model: "Mx-3"},
    {brandId: 21, brand: "MAZDA", modelId: 503, model: "Mx-5"},
    {brandId: 21, brand: "MAZDA", modelId: 504, model: "Mx-6"},
    {brandId: 21, brand: "MAZDA", modelId: 505, model: "Premacy"},
    {brandId: 21, brand: "MAZDA", modelId: 506, model: "Rx-7"},
    {brandId: 21, brand: "MAZDA", modelId: 507, model: "Rx-8"},
    {brandId: 21, brand: "MAZDA", modelId: 508, model: "Tribute"},
    {brandId: 21, brand: "MAZDA", modelId: 509, model: "Xedos"},
    {brandId: 22, brand: "MERCEDES", modelId: 510, model: "190-series"},
    {brandId: 22, brand: "MERCEDES", modelId: 511, model: "200"},
    {brandId: 22, brand: "MERCEDES", modelId: 512, model: "220"},
    {brandId: 22, brand: "MERCEDES", modelId: 513, model: "230"},
    {brandId: 22, brand: "MERCEDES", modelId: 514, model: "240"},
    {brandId: 22, brand: "MERCEDES", modelId: 515, model: "250"},
    {brandId: 22, brand: "MERCEDES", modelId: 516, model: "260"},
    {brandId: 22, brand: "MERCEDES", modelId: 517, model: "280"},
    {brandId: 22, brand: "MERCEDES", modelId: 518, model: "300"},
    {brandId: 22, brand: "MERCEDES", modelId: 519, model: "350"},
    {brandId: 22, brand: "MERCEDES", modelId: 520, model: "400"},
    {brandId: 22, brand: "MERCEDES", modelId: 521, model: "500"},
    {brandId: 22, brand: "MERCEDES", modelId: 522, model: "560"},
    {brandId: 22, brand: "MERCEDES", modelId: 523, model: "AMG"},
    {brandId: 22, brand: "MERCEDES", modelId: 524, model: "AMG GT"},
    {brandId: 22, brand: "MERCEDES", modelId: 525, model: "CLS"},
    {brandId: 22, brand: "MERCEDES", modelId: 526, model: "Citan"},
    {brandId: 22, brand: "MERCEDES", modelId: 527, model: "Citan Combi"},
    {brandId: 22, brand: "MERCEDES", modelId: 528, model: "Classe A"},
    {brandId: 22, brand: "MERCEDES", modelId: 529, model: "Classe B"},
    {brandId: 22, brand: "MERCEDES", modelId: 530, model: "Classe C"},
    {brandId: 22, brand: "MERCEDES", modelId: 531, model: "Classe Cl"},
    {brandId: 22, brand: "MERCEDES", modelId: 532, model: "Classe Cla"},
    {brandId: 22, brand: "MERCEDES", modelId: 533, model: "Classe Clk"},
    {brandId: 22, brand: "MERCEDES", modelId: 534, model: "Classe Cls"},
    {brandId: 22, brand: "MERCEDES", modelId: 535, model: "Classe E"},
    {brandId: 22, brand: "MERCEDES", modelId: 536, model: "Classe G"},
    {brandId: 22, brand: "MERCEDES", modelId: 537, model: "Classe GLE"},
    {brandId: 22, brand: "MERCEDES", modelId: 538, model: "Classe Gl"},
    {brandId: 22, brand: "MERCEDES", modelId: 539, model: "Classe Gla"},
    {brandId: 22, brand: "MERCEDES", modelId: 540, model: "Classe Glk"},
    {brandId: 22, brand: "MERCEDES", modelId: 541, model: "Classe M"},
    {brandId: 22, brand: "MERCEDES", modelId: 542, model: "Classe R"},
    {brandId: 22, brand: "MERCEDES", modelId: 543, model: "Classe S"},
    {brandId: 22, brand: "MERCEDES", modelId: 544, model: "Classe Sl Roadster"},
    {brandId: 22, brand: "MERCEDES", modelId: 545, model: "Classe V"},
    {brandId: 22, brand: "MERCEDES", modelId: 546, model: "EQC"},
    {brandId: 22, brand: "MERCEDES", modelId: 547, model: "GLB"},
    {brandId: 22, brand: "MERCEDES", modelId: 548, model: "GLC"},
    {brandId: 22, brand: "MERCEDES", modelId: 549, model: "GLS"},
    {brandId: 22, brand: "MERCEDES", modelId: 550, model: "MB"},
    {brandId: 22, brand: "MERCEDES", modelId: 551, model: "ML"},
    {brandId: 22, brand: "MERCEDES", modelId: 552, model: "SLC"},
    {brandId: 22, brand: "MERCEDES", modelId: 553, model: "SLS"},
    {brandId: 22, brand: "MERCEDES", modelId: 554, model: "Sl"},
    {brandId: 22, brand: "MERCEDES", modelId: 555, model: "Slk"},
    {brandId: 22, brand: "MERCEDES", modelId: 556, model: "Slr"},
    {brandId: 22, brand: "MERCEDES", modelId: 557, model: "Sls Amg"},
    {brandId: 22, brand: "MERCEDES", modelId: 558, model: "Sprinter"},
    {brandId: 22, brand: "MERCEDES", modelId: 559, model: "V"},
    {brandId: 22, brand: "MERCEDES", modelId: 560, model: "Vaneo"},
    {brandId: 22, brand: "MERCEDES", modelId: 561, model: "Viano"},
    {brandId: 22, brand: "MERCEDES", modelId: 562, model: "Vito"},
    {brandId: 23, brand: "MINI", modelId: 563, model: "Countryman"},
    {brandId: 23, brand: "MINI", modelId: 564, model: "Mini"},
    {brandId: 23, brand: "MINI", modelId: 565, model: "Mini Cabriolet"},
    {brandId: 23, brand: "MINI", modelId: 566, model: "Paceman"},
    {brandId: 24, brand: "NISSAN", modelId: 567, model: "100"},
    {brandId: 24, brand: "NISSAN", modelId: 568, model: "100 Nx"},
    {brandId: 24, brand: "NISSAN", modelId: 569, model: "200"},
    {brandId: 24, brand: "NISSAN", modelId: 570, model: "200 Sx"},
    {brandId: 24, brand: "NISSAN", modelId: 571, model: "300"},
    {brandId: 24, brand: "NISSAN", modelId: 572, model: "300ZX"},
    {brandId: 24, brand: "NISSAN", modelId: 573, model: "350 Z Roadster"},
    {brandId: 24, brand: "NISSAN", modelId: 574, model: "350Z"},
    {brandId: 24, brand: "NISSAN", modelId: 575, model: "370z"},
    {brandId: 24, brand: "NISSAN", modelId: 576, model: "Almera"},
    {brandId: 24, brand: "NISSAN", modelId: 577, model: "Bluebird"},
    {brandId: 24, brand: "NISSAN", modelId: 578, model: "Cedric"},
    {brandId: 24, brand: "NISSAN", modelId: 579, model: "Cherry"},
    {brandId: 24, brand: "NISSAN", modelId: 580, model: "Cube"},
    {brandId: 24, brand: "NISSAN", modelId: 581, model: "Evalia"},
    {brandId: 24, brand: "NISSAN", modelId: 582, model: "Gt-r"},
    {brandId: 24, brand: "NISSAN", modelId: 583, model: "Interstar"},
    {brandId: 24, brand: "NISSAN", modelId: 584, model: "Juke"},
    {brandId: 24, brand: "NISSAN", modelId: 585, model: "Leaf"},
    {brandId: 24, brand: "NISSAN", modelId: 586, model: "Maxima"},
    {brandId: 24, brand: "NISSAN", modelId: 587, model: "Micra"},
    {brandId: 24, brand: "NISSAN", modelId: 588, model: "Murano"},
    {brandId: 24, brand: "NISSAN", modelId: 589, model: "Navara"},
    {brandId: 24, brand: "NISSAN", modelId: 590, model: "Note"},
    {brandId: 24, brand: "NISSAN", modelId: 591, model: "Nv200"},
    {brandId: 24, brand: "NISSAN", modelId: 592, model: "Nv300 Combi"},
    {brandId: 24, brand: "NISSAN", modelId: 593, model: "Nv400 Combi"},
    {brandId: 24, brand: "NISSAN", modelId: 594, model: "Pathfinder"},
    {brandId: 24, brand: "NISSAN", modelId: 595, model: "Patrol"},
    {brandId: 24, brand: "NISSAN", modelId: 596, model: "Pixo"},
    {brandId: 24, brand: "NISSAN", modelId: 597, model: "Prairie"},
    {brandId: 24, brand: "NISSAN", modelId: 598, model: "Primastar"},
    {brandId: 24, brand: "NISSAN", modelId: 599, model: "Primera"},
    {brandId: 24, brand: "NISSAN", modelId: 600, model: "Pulsar"},
    {brandId: 24, brand: "NISSAN", modelId: 601, model: "Qashqai"},
    {brandId: 24, brand: "NISSAN", modelId: 602, model: "Serena"},
    {brandId: 24, brand: "NISSAN", modelId: 603, model: "Silvia"},
    {brandId: 24, brand: "NISSAN", modelId: 604, model: "Stanza"},
    {brandId: 24, brand: "NISSAN", modelId: 605, model: "Sunny"},
    {brandId: 24, brand: "NISSAN", modelId: 606, model: "Terrano"},
    {brandId: 24, brand: "NISSAN", modelId: 607, model: "Vanette"},
    {brandId: 24, brand: "NISSAN", modelId: 608, model: "X-trail"},
    {brandId: 24, brand: "NISSAN", modelId: 609, model: "Z"},
    {brandId: 24, brand: "NISSAN", modelId: 610, model: "Zx"},
    {brandId: 25, brand: "OPEL", modelId: 611, model: "Adam"},
    {brandId: 25, brand: "OPEL", modelId: 612, model: "Agila"},
    {brandId: 25, brand: "OPEL", modelId: 613, model: "Ampera"},
    {brandId: 25, brand: "OPEL", modelId: 614, model: "Antara"},
    {brandId: 25, brand: "OPEL", modelId: 615, model: "Ascona"},
    {brandId: 25, brand: "OPEL", modelId: 616, model: "Astra"},
    {brandId: 25, brand: "OPEL", modelId: 617, model: "Cabrio"},
    {brandId: 25, brand: "OPEL", modelId: 618, model: "Calibra"},
    {brandId: 25, brand: "OPEL", modelId: 619, model: "Cascada"},
    {brandId: 25, brand: "OPEL", modelId: 620, model: "Combo"},
    {brandId: 25, brand: "OPEL", modelId: 621, model: "Commodore"},
    {brandId: 25, brand: "OPEL", modelId: 622, model: "Corsa"},
    {brandId: 25, brand: "OPEL", modelId: 623, model: "Crossland X"},
    {brandId: 25, brand: "OPEL", modelId: 624, model: "Frontera"},
    {brandId: 25, brand: "OPEL", modelId: 625, model: "Grandland X"},
    {brandId: 25, brand: "OPEL", modelId: 626, model: "Gt"},
    {brandId: 25, brand: "OPEL", modelId: 627, model: "Insignia"},
    {brandId: 25, brand: "OPEL", modelId: 628, model: "Kadett"},
    {brandId: 25, brand: "OPEL", modelId: 629, model: "Karl"},
    {brandId: 25, brand: "OPEL", modelId: 630, model: "Manta"},
    {brandId: 25, brand: "OPEL", modelId: 631, model: "Meriva"},
    {brandId: 25, brand: "OPEL", modelId: 632, model: "Mokka"},
    {brandId: 25, brand: "OPEL", modelId: 633, model: "Monterey"},
    {brandId: 25, brand: "OPEL", modelId: 634, model: "Monza"},
    {brandId: 25, brand: "OPEL", modelId: 635, model: "Movano"},
    {brandId: 25, brand: "OPEL", modelId: 636, model: "Omega"},
    {brandId: 25, brand: "OPEL", modelId: 637, model: "Rekord"},
    {brandId: 25, brand: "OPEL", modelId: 638, model: "Senator"},
    {brandId: 25, brand: "OPEL", modelId: 639, model: "Signum"},
    {brandId: 25, brand: "OPEL", modelId: 640, model: "Sintra"},
    {brandId: 25, brand: "OPEL", modelId: 641, model: "Speedster"},
    {brandId: 25, brand: "OPEL", modelId: 642, model: "Tigra"},
    {brandId: 25, brand: "OPEL", modelId: 643, model: "Vectra"},
    {brandId: 25, brand: "OPEL", modelId: 644, model: "Vivaro"},
    {brandId: 25, brand: "OPEL", modelId: 645, model: "Zafira"},
    {brandId: 26, brand: "PEUGEOT", modelId: 646, model: "1007"},
    {brandId: 26, brand: "PEUGEOT", modelId: 647, model: "104"},
    {brandId: 26, brand: "PEUGEOT", modelId: 648, model: "106"},
    {brandId: 26, brand: "PEUGEOT", modelId: 649, model: "107"},
    {brandId: 26, brand: "PEUGEOT", modelId: 650, model: "108"},
    {brandId: 26, brand: "PEUGEOT", modelId: 651, model: "2008"},
    {brandId: 26, brand: "PEUGEOT", modelId: 652, model: "205"},
    {brandId: 26, brand: "PEUGEOT", modelId: 653, model: "206"},
    {brandId: 26, brand: "PEUGEOT", modelId: 654, model: "207"},
    {brandId: 26, brand: "PEUGEOT", modelId: 655, model: "208"},
    {brandId: 26, brand: "PEUGEOT", modelId: 656, model: "3008"},
    {brandId: 26, brand: "PEUGEOT", modelId: 657, model: "305"},
    {brandId: 26, brand: "PEUGEOT", modelId: 658, model: "306"},
    {brandId: 26, brand: "PEUGEOT", modelId: 659, model: "307"},
    {brandId: 26, brand: "PEUGEOT", modelId: 660, model: "308"},
    {brandId: 26, brand: "PEUGEOT", modelId: 661, model: "309"},
    {brandId: 26, brand: "PEUGEOT", modelId: 662, model: "4007"},
    {brandId: 26, brand: "PEUGEOT", modelId: 663, model: "4008"},
    {brandId: 26, brand: "PEUGEOT", modelId: 664, model: "405"},
    {brandId: 26, brand: "PEUGEOT", modelId: 665, model: "406"},
    {brandId: 26, brand: "PEUGEOT", modelId: 666, model: "407"},
    {brandId: 26, brand: "PEUGEOT", modelId: 667, model: "5008"},
    {brandId: 26, brand: "PEUGEOT", modelId: 668, model: "505"},
    {brandId: 26, brand: "PEUGEOT", modelId: 669, model: "508"},
    {brandId: 26, brand: "PEUGEOT", modelId: 670, model: "604"},
    {brandId: 26, brand: "PEUGEOT", modelId: 671, model: "605"},
    {brandId: 26, brand: "PEUGEOT", modelId: 672, model: "607"},
    {brandId: 26, brand: "PEUGEOT", modelId: 673, model: "806"},
    {brandId: 26, brand: "PEUGEOT", modelId: 674, model: "807"},
    {brandId: 26, brand: "PEUGEOT", modelId: 675, model: "Bipper Tepee"},
    {brandId: 26, brand: "PEUGEOT", modelId: 676, model: "Boxer"},
    {brandId: 26, brand: "PEUGEOT", modelId: 677, model: "Cabriolet"},
    {brandId: 26, brand: "PEUGEOT", modelId: 678, model: "Combi"},
    {brandId: 26, brand: "PEUGEOT", modelId: 679, model: "Coupe"},
    {brandId: 26, brand: "PEUGEOT", modelId: 680, model: "Expert"},
    {brandId: 26, brand: "PEUGEOT", modelId: 681, model: "Expert Combi"},
    {brandId: 26, brand: "PEUGEOT", modelId: 682, model: "Ion"},
    {brandId: 26, brand: "PEUGEOT", modelId: 683, model: "J5"},
    {brandId: 26, brand: "PEUGEOT", modelId: 684, model: "J5 Combi"},
    {brandId: 26, brand: "PEUGEOT", modelId: 685, model: "Partner"},
    {brandId: 26, brand: "PEUGEOT", modelId: 686, model: "Rcz"},
    {brandId: 26, brand: "PEUGEOT", modelId: 687, model: "Rifter"},
    {brandId: 26, brand: "PEUGEOT", modelId: 688, model: "Traveller"},
    {brandId: 27, brand: "PORSHE", modelId: 689, model: "911"},
    {brandId: 27, brand: "PORSHE", modelId: 690, model: "918"},
    {brandId: 27, brand: "PORSHE", modelId: 691, model: "918Spyder"},
    {brandId: 27, brand: "PORSHE", modelId: 692, model: "924"},
    {brandId: 27, brand: "PORSHE", modelId: 693, model: "928"},
    {brandId: 27, brand: "PORSHE", modelId: 694, model: "930"},
    {brandId: 27, brand: "PORSHE", modelId: 695, model: "944"},
    {brandId: 27, brand: "PORSHE", modelId: 696, model: "968"},
    {brandId: 27, brand: "PORSHE", modelId: 697, model: "Boxster"},
    {brandId: 27, brand: "PORSHE", modelId: 698, model: "Carrera"},
    {brandId: 27, brand: "PORSHE", modelId: 699, model: "Carrera Gt"},
    {brandId: 27, brand: "PORSHE", modelId: 700, model: "Cayenne"},
    {brandId: 27, brand: "PORSHE", modelId: 701, model: "Cayman"},
    {brandId: 27, brand: "PORSHE", modelId: 702, model: "Macan"},
    {brandId: 27, brand: "PORSHE", modelId: 703, model: "Panamera"},
    {brandId: 27, brand: "PORSHE", modelId: 704, model: "Taycan"},
    {brandId: 28, brand: "RENAULT", modelId: 705, model: "Alpine"},
    {brandId: 28, brand: "RENAULT", modelId: 706, model: "Avantime"},
    {brandId: 28, brand: "RENAULT", modelId: 707, model: "Captur"},
    {brandId: 28, brand: "RENAULT", modelId: 708, model: "Chamade"},
    {brandId: 28, brand: "RENAULT", modelId: 709, model: "Clio"},
    {brandId: 28, brand: "RENAULT", modelId: 710, model: "Espace"},
    {brandId: 28, brand: "RENAULT", modelId: 711, model: "Express"},
    {brandId: 28, brand: "RENAULT", modelId: 712, model: "Fluence"},
    {brandId: 28, brand: "RENAULT", modelId: 713, model: "Fuego"},
    {brandId: 28, brand: "RENAULT", modelId: 714, model: "Kadjar"},
    {brandId: 28, brand: "RENAULT", modelId: 715, model: "Kangoo"},
    {brandId: 28, brand: "RENAULT", modelId: 716, model: "Koleos"},
    {brandId: 28, brand: "RENAULT", modelId: 717, model: "Laguna"},
    {brandId: 28, brand: "RENAULT", modelId: 718, model: "Latitude"},
    {brandId: 28, brand: "RENAULT", modelId: 719, model: "Master"},
    {brandId: 28, brand: "RENAULT", modelId: 720, model: "Megane"},
    {brandId: 28, brand: "RENAULT", modelId: 721, model: "MeganeSedan"},
    {brandId: 28, brand: "RENAULT", modelId: 722, model: "Microbus"},
    {brandId: 28, brand: "RENAULT", modelId: 723, model: "Modus"},
    {brandId: 28, brand: "RENAULT", modelId: 724, model: "Nevada"},
    {brandId: 28, brand: "RENAULT", modelId: 725, model: "Nevada.Phase.2"},
    {brandId: 28, brand: "RENAULT", modelId: 726, model: "R11"},
    {brandId: 28, brand: "RENAULT", modelId: 727, model: "R12"},
    {brandId: 28, brand: "RENAULT", modelId: 728, model: "R13"},
    {brandId: 28, brand: "RENAULT", modelId: 729, model: "R14"},
    {brandId: 28, brand: "RENAULT", modelId: 730, model: "R18"},
    {brandId: 28, brand: "RENAULT", modelId: 731, model: "R19"},
    {brandId: 28, brand: "RENAULT", modelId: 732, model: "R20"},
    {brandId: 28, brand: "RENAULT", modelId: 733, model: "R21"},
    {brandId: 28, brand: "RENAULT", modelId: 734, model: "R25"},
    {brandId: 28, brand: "RENAULT", modelId: 735, model: "R30"},
    {brandId: 28, brand: "RENAULT", modelId: 736, model: "R4"},
    {brandId: 28, brand: "RENAULT", modelId: 737, model: "R5"},
    {brandId: 28, brand: "RENAULT", modelId: 738, model: "R6"},
    {brandId: 28, brand: "RENAULT", modelId: 739, model: "R9"},
    {brandId: 28, brand: "RENAULT", modelId: 740, model: "Safrane"},
    {brandId: 28, brand: "RENAULT", modelId: 741, model: "Scenic"},
    {brandId: 28, brand: "RENAULT", modelId: 742, model: "Spider"},
    {brandId: 28, brand: "RENAULT", modelId: 743, model: "Sport Spider"},
    {brandId: 28, brand: "RENAULT", modelId: 744, model: "Supercinq"},
    {brandId: 28, brand: "RENAULT", modelId: 745, model: "Talisman"},
    {brandId: 28, brand: "RENAULT", modelId: 746, model: "Trafic"},
    {brandId: 28, brand: "RENAULT", modelId: 747, model: "Twingo"},
    {brandId: 28, brand: "RENAULT", modelId: 748, model: "Twizy"},
    {brandId: 28, brand: "RENAULT", modelId: 749, model: "Vel Satis"},
    {brandId: 28, brand: "RENAULT", modelId: 750, model: "Wind"},
    {brandId: 28, brand: "RENAULT", modelId: 751, model: "Zoe"},
    {brandId: 29, brand: "SEAT", modelId: 752, model: "Alhambra"},
    {brandId: 29, brand: "SEAT", modelId: 753, model: "Altea"},
    {brandId: 29, brand: "SEAT", modelId: 754, model: "Arona"},
    {brandId: 29, brand: "SEAT", modelId: 755, model: "Arosa"},
    {brandId: 29, brand: "SEAT", modelId: 756, model: "Ateca"},
    {brandId: 29, brand: "SEAT", modelId: 757, model: "Cordoba"},
    {brandId: 29, brand: "SEAT", modelId: 758, model: "Exeo"},
    {brandId: 29, brand: "SEAT", modelId: 759, model: "ura"},
    {brandId: 29, brand: "SEAT", modelId: 760, model: "Ibiza"},
    {brandId: 29, brand: "SEAT", modelId: 761, model: "IbizaNs"},
    {brandId: 29, brand: "SEAT", modelId: 762, model: "Inca"},
    {brandId: 29, brand: "SEAT", modelId: 763, model: "Leon"},
    {brandId: 29, brand: "SEAT", modelId: 764, model: "Malaga"},
    {brandId: 29, brand: "SEAT", modelId: 765, model: "Marbella"},
    {brandId: 29, brand: "SEAT", modelId: 766, model: "Mii"},
    {brandId: 29, brand: "SEAT", modelId: 767, model: "Ronda"},
    {brandId: 29, brand: "SEAT", modelId: 768, model: "RondaP"},
    {brandId: 29, brand: "SEAT", modelId: 769, model: "Tarraco"},
    {brandId: 29, brand: "SEAT", modelId: 770, model: "Terra"},
    {brandId: 29, brand: "SEAT", modelId: 771, model: "Toledo"},
    {brandId: 30, brand: "ŠKODA", modelId: 772, model: "105"},
    {brandId: 30, brand: "ŠKODA", modelId: 773, model: "1050"},
    {brandId: 30, brand: "ŠKODA", modelId: 774, model: "120"},
    {brandId: 30, brand: "ŠKODA", modelId: 775, model: "130"},
    {brandId: 30, brand: "ŠKODA", modelId: 776, model: "Citigo"},
    {brandId: 30, brand: "ŠKODA", modelId: 777, model: "Coupe"},
    {brandId: 30, brand: "ŠKODA", modelId: 778, model: "Fabia"},
    {brandId: 30, brand: "ŠKODA", modelId: 779, model: "Favorit"},
    {brandId: 30, brand: "ŠKODA", modelId: 780, model: "Felicia"},
    {brandId: 30, brand: "ŠKODA", modelId: 781, model: "Forman"},
    {brandId: 30, brand: "ŠKODA", modelId: 782, model: "Kamiq"},
    {brandId: 30, brand: "ŠKODA", modelId: 783, model: "Karoq"},
    {brandId: 30, brand: "ŠKODA", modelId: 784, model: "Kodiaq"},
    {brandId: 30, brand: "ŠKODA", modelId: 785, model: "Octavia"},
    {brandId: 30, brand: "ŠKODA", modelId: 786, model: "Rapid"},
    {brandId: 30, brand: "ŠKODA", modelId: 787, model: "Roomster"},
    {brandId: 30, brand: "ŠKODA", modelId: 788, model: "Scala"},
    {brandId: 30, brand: "ŠKODA", modelId: 789, model: "Superb"},
    {brandId: 30, brand: "ŠKODA", modelId: 790, model: "Yeti"},
    {brandId: 31, brand: "SUBARU", modelId: 791, model: "B9 Tribeca"},
    {brandId: 31, brand: "SUBARU", modelId: 792, model: "Brz"},
    {brandId: 31, brand: "SUBARU", modelId: 793, model: "E 12"},
    {brandId: 31, brand: "SUBARU", modelId: 794, model: "Forester"},
    {brandId: 31, brand: "SUBARU", modelId: 795, model: "G3x Justy"},
    {brandId: 31, brand: "SUBARU", modelId: 796, model: "Impreza"},
    {brandId: 31, brand: "SUBARU", modelId: 797, model: "Justy"},
    {brandId: 31, brand: "SUBARU", modelId: 798, model: "Legacy"},
    {brandId: 31, brand: "SUBARU", modelId: 799, model: "Levorg"},
    {brandId: 31, brand: "SUBARU", modelId: 800, model: "Outback"},
    {brandId: 31, brand: "SUBARU", modelId: 801, model: "Svx"},
    {brandId: 31, brand: "SUBARU", modelId: 802, model: "Trezia"},
    {brandId: 31, brand: "SUBARU", modelId: 803, model: "Tribeca"},
    {brandId: 31, brand: "SUBARU", modelId: 804, model: "Vanille"},
    {brandId: 31, brand: "SUBARU", modelId: 805, model: "WRX STI"},
    {brandId: 31, brand: "SUBARU", modelId: 806, model: "Xv"},
    {brandId: 32, brand: "SUZUKI", modelId: 807, model: "Alto"},
    {brandId: 32, brand: "SUZUKI", modelId: 808, model: "Baleno"},
    {brandId: 32, brand: "SUZUKI", modelId: 809, model: "Celerio"},
    {brandId: 32, brand: "SUZUKI", modelId: 810, model: "Grand Vitara"},
    {brandId: 32, brand: "SUZUKI", modelId: 811, model: "Ignis"},
    {brandId: 32, brand: "SUZUKI", modelId: 812, model: "Jimny"},
    {brandId: 32, brand: "SUZUKI", modelId: 813, model: "Kizashi"},
    {brandId: 32, brand: "SUZUKI", modelId: 814, model: "Liana"},
    {brandId: 32, brand: "SUZUKI", modelId: 815, model: "Samurai"},
    {brandId: 32, brand: "SUZUKI", modelId: 816, model: "Splash"},
    {brandId: 32, brand: "SUZUKI", modelId: 817, model: "Swift"},
    {brandId: 32, brand: "SUZUKI", modelId: 818, model: "Sx4"},
    {brandId: 32, brand: "SUZUKI", modelId: 819, model: "Vitara"},
    {brandId: 32, brand: "SUZUKI", modelId: 820, model: "Wagon"},
    {brandId: 32, brand: "SUZUKI", modelId: 821, model: "Wagon R"},
    {brandId: 32, brand: "SUZUKI", modelId: 822, model: "X-90"},
    {brandId: 33, brand: "TESLA", modelId: 823, model: "Model 3"},
    {brandId: 33, brand: "TESLA", modelId: 824, model: "Model S"},
    {brandId: 33, brand: "TESLA", modelId: 825, model: "Model X"},
    {brandId: 34, brand: "TOYOTA", modelId: 826, model: "4-runner"},
    {brandId: 34, brand: "TOYOTA", modelId: 827, model: "Auris"},
    {brandId: 34, brand: "TOYOTA", modelId: 828, model: "Avensis"},
    {brandId: 34, brand: "TOYOTA", modelId: 829, model: "Aygo"},
    {brandId: 34, brand: "TOYOTA", modelId: 830, model: "C-hr"},
    {brandId: 34, brand: "TOYOTA", modelId: 831, model: "Camry"},
    {brandId: 34, brand: "TOYOTA", modelId: 832, model: "Carina"},
    {brandId: 34, brand: "TOYOTA", modelId: 833, model: "Celica"},
    {brandId: 34, brand: "TOYOTA", modelId: 834, model: "Corolla"},
    {brandId: 34, brand: "TOYOTA", modelId: 835, model: "Cressida"},
    {brandId: 34, brand: "TOYOTA", modelId: 836, model: "Escape"},
    {brandId: 34, brand: "TOYOTA", modelId: 837, model: "GRSupra"},
    {brandId: 34, brand: "TOYOTA", modelId: 838, model: "Gt86"},
    {brandId: 34, brand: "TOYOTA", modelId: 839, model: "Hi Ace"},
    {brandId: 34, brand: "TOYOTA", modelId: 840, model: "Iq"},
    {brandId: 34, brand: "TOYOTA", modelId: 841, model: "Land Cruiser"},
    {brandId: 34, brand: "TOYOTA", modelId: 842, model: "Lc.Td"},
    {brandId: 34, brand: "TOYOTA", modelId: 843, model: "Lexus"},
    {brandId: 34, brand: "TOYOTA", modelId: 844, model: "Lite-ace"},
    {brandId: 34, brand: "TOYOTA", modelId: 845, model: "Mirai"},
    {brandId: 34, brand: "TOYOTA", modelId: 846, model: "Model"},
    {brandId: 34, brand: "TOYOTA", modelId: 847, model: "Modele F"},
    {brandId: 34, brand: "TOYOTA", modelId: 848, model: "Mr"},
    {brandId: 34, brand: "TOYOTA", modelId: 849, model: "Mr2"},
    {brandId: 34, brand: "TOYOTA", modelId: 850, model: "Paseo"},
    {brandId: 34, brand: "TOYOTA", modelId: 851, model: "Picnic"},
    {brandId: 34, brand: "TOYOTA", modelId: 852, model: "Previa"},
    {brandId: 34, brand: "TOYOTA", modelId: 853, model: "Prius"},
    {brandId: 34, brand: "TOYOTA", modelId: 854, model: "Prius+"},
    {brandId: 34, brand: "TOYOTA", modelId: 855, model: "Proace Combi"},
    {brandId: 34, brand: "TOYOTA", modelId: 856, model: "Proace Verso"},
    {brandId: 34, brand: "TOYOTA", modelId: 857, model: "Rav 4"},
    {brandId: 34, brand: "TOYOTA", modelId: 858, model: "Runner"},
    {brandId: 34, brand: "TOYOTA", modelId: 859, model: "Starlet"},
    {brandId: 34, brand: "TOYOTA", modelId: 860, model: "Supra"},
    {brandId: 34, brand: "TOYOTA", modelId: 861, model: "Tercel"},
    {brandId: 34, brand: "TOYOTA", modelId: 862, model: "Urban Cruiser"},
    {brandId: 34, brand: "TOYOTA", modelId: 863, model: "Verso"},
    {brandId: 34, brand: "TOYOTA", modelId: 864, model: "Yaris"},
    {brandId: 35, brand: "VOLKSWAGEN", modelId: 865, model: "Arteon"},
    {brandId: 35, brand: "VOLKSWAGEN", modelId: 866, model: "Beetle"},
    {brandId: 35, brand: "VOLKSWAGEN", modelId: 867, model: "Bora"},
    {brandId: 35, brand: "VOLKSWAGEN", modelId: 868, model: "Cab."},
    {brandId: 35, brand: "VOLKSWAGEN", modelId: 869, model: "Cabriolet"},
    {brandId: 35, brand: "VOLKSWAGEN", modelId: 870, model: "Caddy"},
    {brandId: 35, brand: "VOLKSWAGEN", modelId: 871, model: "California"},
    {brandId: 35, brand: "VOLKSWAGEN", modelId: 872, model: "Caravelle"},
    {brandId: 35, brand: "VOLKSWAGEN", modelId: 873, model: "Coccinelle"},
    {brandId: 35, brand: "VOLKSWAGEN", modelId: 874, model: "Combi"},
    {brandId: 35, brand: "VOLKSWAGEN", modelId: 875, model: "Corrado"},
    {brandId: 35, brand: "VOLKSWAGEN", modelId: 876, model: "Crafter Combi"},
    {brandId: 35, brand: "VOLKSWAGEN", modelId: 877, model: "Eos"},
    {brandId: 35, brand: "VOLKSWAGEN", modelId: 878, model: "Fox"},
    {brandId: 35, brand: "VOLKSWAGEN", modelId: 879, model: "Golf"},
    {brandId: 35, brand: "VOLKSWAGEN", modelId: 880, model: "Golf Plus"},
    {brandId: 35, brand: "VOLKSWAGEN", modelId: 881, model: "Golf Sportsvan"},
    {brandId: 35, brand: "VOLKSWAGEN", modelId: 882, model: "Jetta"},
    {brandId: 35, brand: "VOLKSWAGEN", modelId: 883, model: "Lt Combi"},
    {brandId: 35, brand: "VOLKSWAGEN", modelId: 884, model: "Lupo"},
    {brandId: 35, brand: "VOLKSWAGEN", modelId: 885, model: "Minibus"},
    {brandId: 35, brand: "VOLKSWAGEN", modelId: 886, model: "Multivan"},
    {brandId: 35, brand: "VOLKSWAGEN", modelId: 887, model: "New Beetle"},
    {brandId: 35, brand: "VOLKSWAGEN", modelId: 888, model: "Passat"},
    {brandId: 35, brand: "VOLKSWAGEN", modelId: 889, model: "Phaeton"},
    {brandId: 35, brand: "VOLKSWAGEN", modelId: 890, model: "Polo"},
    {brandId: 35, brand: "VOLKSWAGEN", modelId: 891, model: "Santana"},
    {brandId: 35, brand: "VOLKSWAGEN", modelId: 892, model: "Scirocco"},
    {brandId: 35, brand: "VOLKSWAGEN", modelId: 893, model: "Sharan"},
    {brandId: 35, brand: "VOLKSWAGEN", modelId: 894, model: "T-cross"},
    {brandId: 35, brand: "VOLKSWAGEN", modelId: 895, model: "T-roc"},
    {brandId: 35, brand: "VOLKSWAGEN", modelId: 896, model: "Tiguan"},
    {brandId: 35, brand: "VOLKSWAGEN", modelId: 897, model: "Tiguan Allspace"},
    {brandId: 35, brand: "VOLKSWAGEN", modelId: 898, model: "Touareg"},
    {brandId: 35, brand: "VOLKSWAGEN", modelId: 899, model: "Touran"},
    {brandId: 35, brand: "VOLKSWAGEN", modelId: 900, model: "Transporter"},
    {brandId: 35, brand: "VOLKSWAGEN", modelId: 901, model: "Up"},
    {brandId: 35, brand: "VOLKSWAGEN", modelId: 902, model: "Variant"},
    {brandId: 35, brand: "VOLKSWAGEN", modelId: 903, model: "Vento"},
    {brandId: 36, brand: "VOLVO", modelId: 904, model: "240"},
    {brandId: 36, brand: "VOLVO", modelId: 905, model: "240 Break"},
    {brandId: 36, brand: "VOLVO", modelId: 906, model: "244"},
    {brandId: 36, brand: "VOLVO", modelId: 907, model: "245"},
    {brandId: 36, brand: "VOLVO", modelId: 908, model: "264"},
    {brandId: 36, brand: "VOLVO", modelId: 909, model: "265"},
    {brandId: 36, brand: "VOLVO", modelId: 910, model: "340 / 360"},
    {brandId: 36, brand: "VOLVO", modelId: 911, model: "343"},
    {brandId: 36, brand: "VOLVO", modelId: 912, model: "345"},
    {brandId: 36, brand: "VOLVO", modelId: 913, model: "440 / 460"},
    {brandId: 36, brand: "VOLVO", modelId: 914, model: "480"},
    {brandId: 36, brand: "VOLVO", modelId: 915, model: "740"},
    {brandId: 36, brand: "VOLVO", modelId: 916, model: "760"},
    {brandId: 36, brand: "VOLVO", modelId: 917, model: "780"},
    {brandId: 36, brand: "VOLVO", modelId: 918, model: "850"},
    {brandId: 36, brand: "VOLVO", modelId: 919, model: "940 / Polar"},
    {brandId: 36, brand: "VOLVO", modelId: 920, model: "960"},
    {brandId: 36, brand: "VOLVO", modelId: 921, model: "C30"},
    {brandId: 36, brand: "VOLVO", modelId: 922, model: "C70"},
    {brandId: 36, brand: "VOLVO", modelId: 923, model: "M40"},
    {brandId: 36, brand: "VOLVO", modelId: 924, model: "S40"},
    {brandId: 36, brand: "VOLVO", modelId: 925, model: "S60"},
    {brandId: 36, brand: "VOLVO", modelId: 926, model: "S70"},
    {brandId: 36, brand: "VOLVO", modelId: 927, model: "S80"},
    {brandId: 36, brand: "VOLVO", modelId: 928, model: "S90"},
    {brandId: 36, brand: "VOLVO", modelId: 929, model: "V40"},
    {brandId: 36, brand: "VOLVO", modelId: 930, model: "V50"},
    {brandId: 36, brand: "VOLVO", modelId: 931, model: "V60"},
    {brandId: 36, brand: "VOLVO", modelId: 932, model: "V70"},
    {brandId: 36, brand: "VOLVO", modelId: 933, model: "V90"},
    {brandId: 36, brand: "VOLVO", modelId: 934, model: "Xc40"},
    {brandId: 36, brand: "VOLVO", modelId: 935, model: "Xc60"},
    {brandId: 36, brand: "VOLVO", modelId: 936, model: "Xc70"},
    {brandId: 36, brand: "VOLVO", modelId: 937, model: "Xc90"}
  ]);


  types :BehaviorSubject<any[]> = new BehaviorSubject([
    {name: "4 X 4"},
    {name: "Berline"},
    {name: "Break"},
    {name: "Cabriolet"},
    {name: "Citadine"},
    {name: "Compacte"},
    {name: "Coupé"},
    {name: "Monospace"},
    {name: "Sportive"},
    {name: "Suv"},
    {name: "Utilitaires"},
    {name: "Autres"}
  ]);
  carburants:BehaviorSubject<any[]> = new BehaviorSubject([
    {name: "Autres"},
    {name: "Diesel"},
    {name: "Electrique"},
    {name: "Essence"},
    {name: "Hybride"}
  ]);


  constructor() {
  }


}
